# Generated by Django 3.1.7 on 2021-04-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='simulationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sratLocs', models.JSONField()),
                ('peopleCount', models.FloatField(default=0)),
                ('endLocs', models.JSONField()),
                ('endCapacity', models.FloatField(default=0)),
                ('emergencyLocs', models.JSONField()),
                ('emergencyCapacity', models.FloatField(default=0)),
                ('dangerLocs', models.JSONField()),
                ('dangerPossibility', models.FloatField(default=0)),
            ],
        ),
    ]
